version: '3.7'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
#    env_file:
#      - ./.env
  web:
    image:
      vdoserg/yamdb:latest
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
    command:
      sh -c "python manage.py migrate --noinput && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/static
    expose:
      - "8000"
    depends_on:
      - db
#    env_file:
#      - ./.env
  nginx:
    image: nginx:1.19.4-alpine
    environment:
      NGINX_PORT: $NGINX_PORT
      NGINX_SERVER_NAME: $NGINX_SERVER_NAME
    restart: always
    volumes:
      - static_volume:/code/static
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "8000:80"
#    env_file:
#      - ./.env
    depends_on:
      - web
