version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    image:
      vdoserg/yamdb_final:latest
    restart: always
    command: sh -c "python manage.py migrate && gunicorn api_yamdb:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx
    restart: always
    volumes:
      - static_volume:/code/static
      - ./nginx/temlates:/etc/nginx/templates
    ports:
      - "8000:80"
    env_file:
      - ./.env
    depends_on:
      - web
