name: Yamdb-final workflow

on: [push]
jobs:
  tests:  
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up python
          uses: action/setup-python@v2
          with:
            python-version: 3.8
            
        - name: Install dependecies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            pip install -r requirements.txt
            
        - name: Lint with flake8
          run: flake8 . --exclude *migrations*,tests,api_yamdb
        
        - name: Test with pytest
          run: pytest
